name: Pre-Releae Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - dev
  workflow_run:
    workflows:
      - 'TEST Workflow'
    types:
      - completed

jobs:
  dummy-job:
    name: Dummy Job
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Step
        run: echo "This is a dummy job"

  pre-release:
    name: Second Job
    needs:
      dummy-job
      #if: ${{ github.event_name == 'pull_request' && github.base_ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: just to show
        run: echo ${{ github.base_ref }}

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download artifacts from "TEST Workflow"
        uses: actions/download-artifact@v3
        with:
          name: package_artifacts
          path: packages

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Check changeset status
        run: npx changeset status --since=origin/dev

      - name: Prepare changeset
        run: npx changeset pre enter ergo

      - name: Update changeset version
        run: |
          sed -i "s/ergo/next-${{ github.sha }}/g" .changeset/pre.json
          npx changeset version

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish changeset
        run: npx changeset publish
